version: "3"
services:
  mariadb:
    image: mariadb
    container_name: mariadba3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: POPFILM
    volumes:
      - mariadb_dataa3:/var/lib/mysql
      - ./Peliculas.sql:/docker-entrypoint-initdb.d/Peliculas.sql
    user: mysql
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina3
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7003:80
    depends_on:
      - mariadb
  python:
    build: .
    container_name: pythona3
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: POPFILM
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      SECRET_KEY: 'you-will-never-guess'
      DEBUG: False
      PYTHONBUFFERED: 1
    volumes:
      - ./uploads:/uploads 
    depends_on:
      - mariadb
  apache:
    build: ./web/apache
    container_name: apachea3
    volumes: 
      - ./web/python/static:/var/www/html
      - ./uploads:/var/www/html/uploads
    ports:
      - 6003:80
    depends_on:
      - python
volumes:
  mariadb_dataa3:


